CREATE USER project2Manager IDENTIFIED BY p2Password;
GRANT CREATE SESSION TO project2Manager;
GRANT UNLIMITED TABLESPACE TO project2Manager;
GRANT CREATE TABLE TO project2Manager;
GRANT CREATE VIEW TO project2Manager;
GRANT CREATE SEQUENCE TO project2Manager;
GRANT CREATE TRIGGER TO project2Manager;

